version: 2
jobs:
  build:
    working_directory: ~/ntcir-datasearch/anserini
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout:
          path: ~/ntcir-datasearch
      - run: git submodule update -i
      - restore_cache:
          key: circleci-java-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-java-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results: 
          path: target/surefire-reports
