version: 2
jobs:
  build:
    working_directory: ~/ntcir-datasearch
    docker:
      - image: mpkato/openjdk11-python3:latest
    steps:
      - checkout:
          path: ~/ntcir-datasearch
      - run: pip install -r requirements.txt
      - run: invoke build
      - store_test_results: 
          path: anserini/target/surefire-reports
