version: 2
jobs:
  build:
    working_directory: ~/ntcir-datasearch
    docker:
      - image: mpkato/openjdk11-python3:latest
    steps:
      - checkout:
          path: ~/ntcir-datasearch
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - run: ~/.poetry/bin/poetry install
      - run: ~/.poetry/bin/poetry run python invoke build
      - store_test_results: 
          path: anserini/target/surefire-reports
