version: 2
jobs:
  build:
    working_directory: ~/ntcir-datasearch
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout:
          path: ~/ntcir-datasearch
      - run: pip install -r requirements.txt
      - run: invoke submodule
      - restore_cache:
          key: circleci-java-{{ checksum "anserini/pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-java-{{ checksum "anserini/pom.xml" }}
      - run: invoke build
      - store_test_results: 
          path: anserini/target/surefire-reports
